name: C/C++ CI

on: [push]

env: 
    APP_PATH: "SharedBuffer/module"
    TEST_PATH: "SharedBuffer/tests"

jobs:
  build:

    runs-on: ubuntu-latest
      
    steps:
    
    - name: Downloading the repository
      uses: actions/checkout@v1
        
    - name: Build module
      run: |
        cd ${{ env.APP_PATH }}
        make
        
    - name: Inserting the module
      run: |
        cd ${{ env.APP_PATH }}
        sudo ls
        sudo insmod SharedBuffer.ko deviceCount=1
    
    - name: Install boost test framework
      run: |
        sudo apt-get install libboost-test-dev
    
    - name: Testing
      run: |
        cd ${{ env.TEST_PATH }}
        make
        sudo ./test --result_code=no --report_level=short
    
    
