name: C/C++ CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Downloading the repository
      uses: actions/checkout@v1
      
    - name: Test
      run: |
        ls
        
    - name: Build module
      run: |
        cd SharedBuffer/module
        make
        
    - name: Inserting the module and test it
      run: |
        sudo insmod SharedBuffer.ko
        lsmod | grep SharedBuffer.ko
      
    
    
